name: Build WF
on:
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v11

      - name: Maven Build
        run: mvn install

  Testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Run test on main branch
        run: mven test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle
